### ISSUE TITLE
Issues with searching

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#42]
Hi,

Okay so I did the mistake of not updating PHUB to your newest commits, which is why I got some of the errors, which you actually have fixed before. But I got some new errors, which I also want to report.

# Searching

If I do a basic search like this:

```python
model = c.search("Mia Khalifa")
for video in model:
    print(video.title)
```

I get an `AssertionError: Account is not logged in` which I am not sure if this is expected
or a mistake, because why would I need to log in to search.

If I log in to my account, it works, but it's extemely slow. With hub traffic and without.
Doesn't make a difference.

If I do a user search like above, but with `c.search_user`, I get this error:

``` 
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/tests.py", line 6, in <module>
    for video in model:
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 126, in __iter__
    for item in page:
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 40, in Page
    and 'premiumIcon' in wrapped._as_query['markers']):
                         ^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute '_as_query'
```
(Also when I am logged in.)

**Comment by Egsagon** [comment]
My bad, video filtering was set on all query types

**Comment by EchterAlsFake** [comment]
Hi, 

today I tried it again, with your newest commit `2828dc547e05c1660d677a723035bb3d20cbd9e7`

Unfortunately I still got the error. I also created a complete new environment to make sure it's not an issue from my local dev environment. Could you maybe have a look on it?  Thanks :)

**Comment by Egsagon** [comment]
Hey, i don't get the error with the latest commit. I just had not changed the version number. I released it now, try to install it from pypi or this repo.

**Comment by EchterAlsFake** [comment]
I somehow still get the error. I compared my query.py with your query.py and it's entirely the same. I am a bit confused now xD.

Getting the object like this:

`search = c.search_user(username="Mia")`

works. Is it right to iterate through the videos like this:

```python
for query in search:
    print(query.name)
```

or is that wrong? 

The lines in which the error happened also changed from yesterday:

```
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/tests.py", line 4, in <module>
    for query in search:
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 105, in __iter__
    for item in page:
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 313, in _iter_page
    and 'premiumIcon' in wrapped._as_query['markers']):
                         ^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute '_as_query'
```

**Comment by Egsagon** [comment]
Should work now.

**Comment by EchterAlsFake** [comment]
Works, thank you :)
